//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Analyzer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Analyzer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Analyzer", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of records can be exported at one time is 1,00,000. Please apply an appropriate date filter..
        /// </summary>
        internal static string EXPORT_LIMIT_CROSSED {
            get {
                return ResourceManager.GetString("EXPORT_LIMIT_CROSSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        internal static string FILTER_CLEAR_HOVER_TEXT {
            get {
                return ResourceManager.GetString("FILTER_CLEAR_HOVER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have applied filter from **** to ####..
        /// </summary>
        internal static string FILTER_HOVER_TEXT {
            get {
                return ResourceManager.GetString("FILTER_HOVER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid From date.
        /// </summary>
        internal static string FILTER_INVALID_FROM_DATE {
            get {
                return ResourceManager.GetString("FILTER_INVALID_FROM_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid To date.
        /// </summary>
        internal static string FILTER_INVALID_TO_DATE {
            get {
                return ResourceManager.GetString("FILTER_INVALID_TO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second date should be greater than first..
        /// </summary>
        internal static string FILTER_TO_DATE_SMALLER {
            get {
                return ResourceManager.GetString("FILTER_TO_DATE_SMALLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong. Please try again after some time..
        /// </summary>
        internal static string GENERAL_EXCEPTION_MSG {
            get {
                return ResourceManager.GetString("GENERAL_EXCEPTION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager list is empty!.
        /// </summary>
        internal static string MANAGER_LIST_EMPTY {
            get {
                return ResourceManager.GetString("MANAGER_LIST_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users assigned!.
        /// </summary>
        internal static string MANAGER_NO_USER_ASSIGNED {
            get {
                return ResourceManager.GetString("MANAGER_NO_USER_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to display!.
        /// </summary>
        internal static string NO_RECORD_TO_DISPLAY {
            get {
                return ResourceManager.GetString("NO_RECORD_TO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subject found..
        /// </summary>
        internal static string SUBJECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SUBJECT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a subject from the drop down list..
        /// </summary>
        internal static string USER_TRAINING_SUBJECT_NULL {
            get {
                return ResourceManager.GetString("USER_TRAINING_SUBJECT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user from the drop down list..
        /// </summary>
        internal static string USER_TRAINING_USER_NULL {
            get {
                return ResourceManager.GetString("USER_TRAINING_USER_NULL", resourceCulture);
            }
        }
    }
}
