//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Editor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Editor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Editor", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to delete this Admin?.
        /// </summary>
        internal static string ADMIN_CONFIRM_DELETION {
            get {
                return ResourceManager.GetString("ADMIN_CONFIRM_DELETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Admin available.
        /// </summary>
        internal static string ADMIN_NO_DATA {
            get {
                return ResourceManager.GetString("ADMIN_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet Only.
        /// </summary>
        internal static string ALPHABET_ONLY {
            get {
                return ResourceManager.GetString("ALPHABET_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Selected User?.
        /// </summary>
        internal static string AO_CONFIRM_USER_DELETE {
            get {
                return ResourceManager.GetString("AO_CONFIRM_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Selected. Please select user!.
        /// </summary>
        internal static string AO_NO_USER_SELECTED {
            get {
                return ResourceManager.GetString("AO_NO_USER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User to Delete!.
        /// </summary>
        internal static string AO_NO_USER_TO_DELETE {
            get {
                return ResourceManager.GetString("AO_NO_USER_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Role!.
        /// </summary>
        internal static string AO_SELECT_ROLE {
            get {
                return ResourceManager.GetString("AO_SELECT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner added successfully!.
        /// </summary>
        internal static string BANNER_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("BANNER_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner deleted successfully!.
        /// </summary>
        internal static string BANNER_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("BANNER_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type. Only png, jpeg, jpg and gif are allowed..
        /// </summary>
        internal static string BANNER_IMAGE_TYPES_INVALID {
            get {
                return ResourceManager.GetString("BANNER_IMAGE_TYPES_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner image height should be between 270px to 300px and width should be more than 1350px..
        /// </summary>
        internal static string BANNER_IMG_DIMENSIONS {
            get {
                return ResourceManager.GetString("BANNER_IMG_DIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image..
        /// </summary>
        internal static string BANNER_IMG_SELECT {
            get {
                return ResourceManager.GetString("BANNER_IMG_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size exceeds 10MB..
        /// </summary>
        internal static string BANNER_IMG_SIZE {
            get {
                return ResourceManager.GetString("BANNER_IMG_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 5 banners can be added..
        /// </summary>
        internal static string BANNER_LIMIT {
            get {
                return ResourceManager.GetString("BANNER_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner re-ordered successfully!.
        /// </summary>
        internal static string BANNER_REORDER_SUCCESS {
            get {
                return ResourceManager.GetString("BANNER_REORDER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner details updated successfully!.
        /// </summary>
        internal static string BANNER_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("BANNER_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter cannot be left blank.
        /// </summary>
        internal static string CHAPTER_BLANK {
            get {
                return ResourceManager.GetString("CHAPTER_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be left blank, please write some text.
        /// </summary>
        internal static string CHAPTER_DATA_EMPTY {
            get {
                return ResourceManager.GetString("CHAPTER_DATA_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Tutorial.
        /// </summary>
        internal static string CHAPTER_DUPLICATE {
            get {
                return ResourceManager.GetString("CHAPTER_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with only .doc and .docx extensions are allowed.
        /// </summary>
        internal static string CHAPTER_FILE_FORMAT_INVALID {
            get {
                return ResourceManager.GetString("CHAPTER_FILE_FORMAT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file.
        /// </summary>
        internal static string CHAPTER_FILE_NOT_SELECTED {
            get {
                return ResourceManager.GetString("CHAPTER_FILE_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size cannot be greater than 50 MB.
        /// </summary>
        internal static string CHAPTER_FILE_SIZE_EXCEEDS {
            get {
                return ResourceManager.GetString("CHAPTER_FILE_SIZE_EXCEEDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload again..
        /// </summary>
        internal static string CHAPTER_FILE_UPLOAD_ERROR {
            get {
                return ResourceManager.GetString("CHAPTER_FILE_UPLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully. Please click on save button to save changes..
        /// </summary>
        internal static string CHAPTER_FILE_UPLOAD_SUCCESS {
            get {
                return ResourceManager.GetString("CHAPTER_FILE_UPLOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format..
        /// </summary>
        internal static string CHAPTER_INVALID_FILE_TYPE {
            get {
                return ResourceManager.GetString("CHAPTER_INVALID_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Chapter Name.
        /// </summary>
        internal static string CHAPTER_INVALID_NAME {
            get {
                return ResourceManager.GetString("CHAPTER_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter has been saved successfully.
        /// </summary>
        internal static string CHAPTER_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("CHAPTER_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check uploaded word document is not open anywhere else..
        /// </summary>
        internal static string CHAPTER_WORD_FILE_NOT_ACCESSIBLE {
            get {
                return ResourceManager.GetString("CHAPTER_WORD_FILE_NOT_ACCESSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to copy this subject?.
        /// </summary>
        internal static string COPY_TEMP_CONFIRM {
            get {
                return ResourceManager.GetString("COPY_TEMP_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Training available.
        /// </summary>
        internal static string COPY_TEMP_NO_TRAINING {
            get {
                return ResourceManager.GetString("COPY_TEMP_NO_TRAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP for account login.
        /// </summary>
        internal static string CP_SUBJECT {
            get {
                return ResourceManager.GetString("CP_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Detail not deleted.Please try again..
        /// </summary>
        internal static string EDITOR_FAQ_DELETE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_FAQ_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Detail Deleted successfully..
        /// </summary>
        internal static string EDITOR_FAQ_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("EDITOR_FAQ_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Name not updated, Please try again..
        /// </summary>
        internal static string EDITOR_FAQ_NAME_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_FAQ_NAME_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Name updated successfully..
        /// </summary>
        internal static string EDITOR_FAQ_NAME_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("EDITOR_FAQ_NAME_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not deleted, Please try again..
        /// </summary>
        internal static string EDITOR_FAQ_QUESTION_DELETE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_FAQ_QUESTION_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ detail not saved,Please try again..
        /// </summary>
        internal static string EDITOR_FAQ_SAVE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_FAQ_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ detail successfully saved..
        /// </summary>
        internal static string EDITOR_FAQ_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("EDITOR_FAQ_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Detail can not be Updated, Please try again..
        /// </summary>
        internal static string EDITOR_FAQ_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_FAQ_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Detail Updated successfully..
        /// </summary>
        internal static string EDITOR_FAQ_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("EDITOR_FAQ_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Videos To Display.
        /// </summary>
        internal static string EDITOR_MYVIDEO_NO_VIDEO_MESSAGE {
            get {
                return ResourceManager.GetString("EDITOR_MYVIDEO_NO_VIDEO_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option A.
        /// </summary>
        internal static string EDITOR_QUIZ_OPTION_A_EMPTY {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_OPTION_A_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option B.
        /// </summary>
        internal static string EDITOR_QUIZ_OPTION_B_EMPTY {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_OPTION_B_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option C.
        /// </summary>
        internal static string EDITOR_QUIZ_OPTION_C_EMPTY {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_OPTION_C_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option D.
        /// </summary>
        internal static string EDITOR_QUIZ_OPTION_D_EMPTY {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_OPTION_D_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option E.
        /// </summary>
        internal static string EDITOR_QUIZ_OPTION_E_EMPTY {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_OPTION_E_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option F.
        /// </summary>
        internal static string EDITOR_QUIZ_OPTION_F_EMPTY {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_OPTION_F_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QuestionId.
        /// </summary>
        internal static string EDITOR_QUIZ_QUESTION_DELETE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_QUESTION_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Deleted Successfully.
        /// </summary>
        internal static string EDITOR_QUIZ_QUESTION_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_QUESTION_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter question.
        /// </summary>
        internal static string EDITOR_QUIZ_QUESTION_EMPTY {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_QUESTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question cannot be inserted!.
        /// </summary>
        internal static string EDITOR_QUIZ_QUESTION_SAVE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_QUESTION_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Question is Saved Successfully!.
        /// </summary>
        internal static string EDITOR_QUIZ_QUESTION_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_QUESTION_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question cannot be updated!.
        /// </summary>
        internal static string EDITOR_QUIZ_QUESTION_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_QUESTION_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Question is Updated Successfully!.
        /// </summary>
        internal static string EDITOR_QUIZ_QUESTION_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("EDITOR_QUIZ_QUESTION_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is successfully uploaded..
        /// </summary>
        internal static string EDITOR_SLIDE_FILE_UPLOADED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("EDITOR_SLIDE_FILE_UPLOADED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected..
        /// </summary>
        internal static string EDITOR_SLIDE_NO_FILE_SELECTED {
            get {
                return ResourceManager.GetString("EDITOR_SLIDE_NO_FILE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not deleted.Please try again..
        /// </summary>
        internal static string EDITOR_SURVEY_DELETE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_SURVEY_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey name not update, please try again..
        /// </summary>
        internal static string EDITOR_SURVEY_NAME_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_SURVEY_NAME_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey name updated successfully..
        /// </summary>
        internal static string EDITOR_SURVEY_NAME_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("EDITOR_SURVEY_NAME_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one option is required..
        /// </summary>
        internal static string EDITOR_SURVEY_NO_OPTION_MESSAGE {
            get {
                return ResourceManager.GetString("EDITOR_SURVEY_NO_OPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not deleted.Please try again..
        /// </summary>
        internal static string EDITOR_SURVEY_QUESTION_DELETE_FAILED {
            get {
                return ResourceManager.GetString("EDITOR_SURVEY_QUESTION_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! An error occurred. Please try again later..
        /// </summary>
        internal static string ERROR_OCCURRED {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write some text, Flashcard back side can not be empty.
        /// </summary>
        internal static string FC_BACK_EMPTY {
            get {
                return ResourceManager.GetString("FC_BACK_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this flashcard?.
        /// </summary>
        internal static string FC_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("FC_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write some text, Flashcard Front side can not be empty.
        /// </summary>
        internal static string FC_FRONT_EMPTY {
            get {
                return ResourceManager.GetString("FC_FRONT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcard has been successfully saved.
        /// </summary>
        internal static string FC_SAVED_SUCCESS {
            get {
                return ResourceManager.GetString("FC_SAVED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature assigned successfully..
        /// </summary>
        internal static string FEATURE_ASSIGN_SUCCESSFULL {
            get {
                return ResourceManager.GetString("FEATURE_ASSIGN_SUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds maximum limit 1 MB..
        /// </summary>
        internal static string FILE_SIZE_EXCEEDS {
            get {
                return ResourceManager.GetString("FILE_SIZE_EXCEEDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string FP_CHANGE_PWD_CONFIRM {
            get {
                return ResourceManager.GetString("FP_CHANGE_PWD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string FP_CHANGE_PWD_NEW_PWD {
            get {
                return ResourceManager.GetString("FP_CHANGE_PWD_NEW_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your one time password (OTP).
        /// </summary>
        internal static string FP_CHANGE_PWD_OTP {
            get {
                return ResourceManager.GetString("FP_CHANGE_PWD_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        internal static string FP_EMAIL_BOX {
            get {
                return ResourceManager.GetString("FP_EMAIL_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Id.
        /// </summary>
        internal static string FP_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("FP_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAGmob.
        /// </summary>
        internal static string FP_MAIL_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("FP_MAIL_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! An error occurred while sending mail to registerd email id. Please try again later..
        /// </summary>
        internal static string FP_MAIL_FAILURE {
            get {
                return ResourceManager.GetString("FP_MAIL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Expired!.
        /// </summary>
        internal static string FP_OTP_EXPIRED {
            get {
                return ResourceManager.GetString("FP_OTP_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s change the password.
        /// </summary>
        internal static string FP_OTP_SUCCESS_BTN_TEXT {
            get {
                return ResourceManager.GetString("FP_OTP_SUCCESS_BTN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password does not match !.
        /// </summary>
        internal static string FP_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("FP_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 4 to 12 characters long.
        /// </summary>
        internal static string FP_PASS_LIMITATION {
            get {
                return ResourceManager.GetString("FP_PASS_LIMITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully changed your password.
        /// </summary>
        internal static string FP_PWD_CHANGE_SUCCESS {
            get {
                return ResourceManager.GetString("FP_PWD_CHANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP to reset password.
        /// </summary>
        internal static string FP_SUBJECT {
            get {
                return ResourceManager.GetString("FP_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for sign-in information was submitted. Please check your email and sign in to continue..
        /// </summary>
        internal static string FP_SUCCESS {
            get {
                return ResourceManager.GetString("FP_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Training available.
        /// </summary>
        internal static string HOME_NO_TRAINING {
            get {
                return ResourceManager.GetString("HOME_NO_TRAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format. Only .png,.jpg and .jpeg files allowed..
        /// </summary>
        internal static string INVALID_IMAGE_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_IMAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format. Only .jpg and .jpeg files allowed..
        /// </summary>
        internal static string INVALID_IMAGE_FORMAT_SPLASH {
            get {
                return ResourceManager.GetString("INVALID_IMAGE_FORMAT_SPLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid task name. Only alphanumeric and  # &apos; ` _ ? :!@$£%^&amp;.*,()+ - characters are allowed..
        /// </summary>
        internal static string INVALID_TASK_TITLE {
            get {
                return ResourceManager.GetString("INVALID_TASK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid training name. Only alphanumeric and  # &apos; ` _ ? : - characters are allowed..
        /// </summary>
        internal static string INVALID_TRAINING_TITLE {
            get {
                return ResourceManager.GetString("INVALID_TRAINING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed only 500 characters..
        /// </summary>
        internal static string ITEM_DISCRIPTION_CHANRECTER_LIMIT_500 {
            get {
                return ResourceManager.GetString("ITEM_DISCRIPTION_CHANRECTER_LIMIT_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Id.
        /// </summary>
        internal static string LOGIN_BLANK_OR_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("LOGIN_BLANK_OR_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Package.
        /// </summary>
        internal static string LOGIN_CONFIRM_PACKAGE {
            get {
                return ResourceManager.GetString("LOGIN_CONFIRM_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email Address.
        /// </summary>
        internal static string LOGIN_EMAIL_BLANK {
            get {
                return ResourceManager.GetString("LOGIN_EMAIL_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string LOGIN_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("LOGIN_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Password.
        /// </summary>
        internal static string LOGIN_PASSWORD_BLANK {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string LOGIN_PASS_BLANK {
            get {
                return ResourceManager.GetString("LOGIN_PASS_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subject already exists.
        /// </summary>
        internal static string MH_DUPLICATE_SUBJECT {
            get {
                return ResourceManager.GetString("MH_DUPLICATE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Milestone?.
        /// </summary>
        internal static string MILESTONE_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("MILESTONE_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This milestone already exists.
        /// </summary>
        internal static string MILESTONE_DUPLICATE {
            get {
                return ResourceManager.GetString("MILESTONE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Milestone Name.
        /// </summary>
        internal static string MILESTONE_INVALID_NAME {
            get {
                return ResourceManager.GetString("MILESTONE_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string MILESTONE_ORDER_ERROR {
            get {
                return ResourceManager.GetString("MILESTONE_ORDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Notification can not be Delivered to {0} users!.
        /// </summary>
        internal static string NOTIFICATION_FAILED {
            get {
                return ResourceManager.GetString("NOTIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Notification Successfully Delivered to {0} users!.
        /// </summary>
        internal static string NOTIFICATION_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Notification Successfully Delivered to {0} / {1} users!.
        /// </summary>
        internal static string NOTIFICATION_SUCCESSFULLY_FAILED {
            get {
                return ResourceManager.GetString("NOTIFICATION_SUCCESSFULLY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data To Display!.
        /// </summary>
        internal static string NO_DATA_TO_DISPLAY {
            get {
                return ResourceManager.GetString("NO_DATA_TO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subject found.
        /// </summary>
        internal static string NO_SUBJECT_FOUND {
            get {
                return ResourceManager.GetString("NO_SUBJECT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string ORDERING_ERROR {
            get {
                return ResourceManager.GetString("ORDERING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases available.
        /// </summary>
        internal static string ORG_ALIAS_AVAILABLE {
            get {
                return ResourceManager.GetString("ORG_ALIAS_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases not available.
        /// </summary>
        internal static string ORG_ALIAS_UNAVAILABLE {
            get {
                return ResourceManager.GetString("ORG_ALIAS_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to delete this Organization?.
        /// </summary>
        internal static string ORG_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("ORG_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id available.
        /// </summary>
        internal static string ORG_EMAIL_AVAILABLE {
            get {
                return ResourceManager.GetString("ORG_EMAIL_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Email Id.
        /// </summary>
        internal static string ORG_EMAIL_NULL {
            get {
                return ResourceManager.GetString("ORG_EMAIL_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id not available.
        /// </summary>
        internal static string ORG_EMAIL_UNAVAILABLE {
            get {
                return ResourceManager.GetString("ORG_EMAIL_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid First Name.
        /// </summary>
        internal static string ORG_INVALID_FIRST_NAME {
            get {
                return ResourceManager.GetString("ORG_INVALID_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Last Name.
        /// </summary>
        internal static string ORG_INVALID_LAST_NAME {
            get {
                return ResourceManager.GetString("ORG_INVALID_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Organization Title.
        /// </summary>
        internal static string ORG_INVALID_TITLE {
            get {
                return ResourceManager.GetString("ORG_INVALID_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No organization available.
        /// </summary>
        internal static string ORG_LIST_BLANK {
            get {
                return ResourceManager.GetString("ORG_LIST_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name not available.
        /// </summary>
        internal static string ORG_NAME_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("ORG_NAME_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name available.
        /// </summary>
        internal static string ORG_NAME_AVAILABLE {
            get {
                return ResourceManager.GetString("ORG_NAME_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name Already Exist.
        /// </summary>
        internal static string ORG_NAME_EXIST {
            get {
                return ResourceManager.GetString("ORG_NAME_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Organization Name.
        /// </summary>
        internal static string ORG_NAME_NULL {
            get {
                return ResourceManager.GetString("ORG_NAME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 4 and Maximum 12 characters required..
        /// </summary>
        internal static string ORG_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("ORG_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These passwords don&apos;t match. Try again?.
        /// </summary>
        internal static string ORG_PASSWORD_NOT_MATCHED {
            get {
                return ResourceManager.GetString("ORG_PASSWORD_NOT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select check box for correct answer.
        /// </summary>
        internal static string QUIZ_CORRECT_ANS_NOT_SELECTED {
            get {
                return ResourceManager.GetString("QUIZ_CORRECT_ANS_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QuestionId.
        /// </summary>
        internal static string QUIZ_INVALID_QUES {
            get {
                return ResourceManager.GetString("QUIZ_INVALID_QUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose single option as correct answer. Multiple answers are not allowed.
        /// </summary>
        internal static string QUIZ_MULTIPLE_ANS {
            get {
                return ResourceManager.GetString("QUIZ_MULTIPLE_ANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option A.
        /// </summary>
        internal static string QUIZ_OPT_A_NULL {
            get {
                return ResourceManager.GetString("QUIZ_OPT_A_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option B.
        /// </summary>
        internal static string QUIZ_OPT_B_NULL {
            get {
                return ResourceManager.GetString("QUIZ_OPT_B_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option C.
        /// </summary>
        internal static string QUIZ_OPT_C_NULL {
            get {
                return ResourceManager.GetString("QUIZ_OPT_C_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option D.
        /// </summary>
        internal static string QUIZ_OPT_D_NULL {
            get {
                return ResourceManager.GetString("QUIZ_OPT_D_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option E.
        /// </summary>
        internal static string QUIZ_OPT_E_NULL {
            get {
                return ResourceManager.GetString("QUIZ_OPT_E_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Option F.
        /// </summary>
        internal static string QUIZ_OPT_F_NULL {
            get {
                return ResourceManager.GetString("QUIZ_OPT_F_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Question?.
        /// </summary>
        internal static string QUIZ_QUES_CONFIRM_DELETION {
            get {
                return ResourceManager.GetString("QUIZ_QUES_CONFIRM_DELETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Deleted Successfully.
        /// </summary>
        internal static string QUIZ_QUES_DELETED {
            get {
                return ResourceManager.GetString("QUIZ_QUES_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter question.
        /// </summary>
        internal static string QUIZ_QUES_EMPTY {
            get {
                return ResourceManager.GetString("QUIZ_QUES_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Question is Saved Successfully!.
        /// </summary>
        internal static string QUIZ_QUES_SAVED {
            get {
                return ResourceManager.GetString("QUIZ_QUES_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Question is Updated Successfully!.
        /// </summary>
        internal static string QUIZ_QUES_UPDATED {
            get {
                return ResourceManager.GetString("QUIZ_QUES_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check entered details..
        /// </summary>
        internal static string SETTING_INVALID_DETAIL {
            get {
                return ResourceManager.GetString("SETTING_INVALID_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string SIGNIN_USER_LOGIN_AS_ADMIN {
            get {
                return ResourceManager.GetString("SIGNIN_USER_LOGIN_AS_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superadmin.
        /// </summary>
        internal static string SIGNIN_USER_LOGIN_AS_SUPERADMIN {
            get {
                return ResourceManager.GetString("SIGNIN_USER_LOGIN_AS_SUPERADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        internal static string SIGNIN_USER_LOGIN_AS_TRAINER {
            get {
                return ResourceManager.GetString("SIGNIN_USER_LOGIN_AS_TRAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email id already exists..
        /// </summary>
        internal static string SIGNUP_EMAILID_ALREADY_EXIST_PART_1 {
            get {
                return ResourceManager.GetString("SIGNUP_EMAILID_ALREADY_EXIST_PART_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try with another email id..
        /// </summary>
        internal static string SIGNUP_EMAILID_ALREADY_EXIST_PART_2 {
            get {
                return ResourceManager.GetString("SIGNUP_EMAILID_ALREADY_EXIST_PART_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again..
        /// </summary>
        internal static string SIGNUP_EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("SIGNUP_EXCEPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet the password policy requirements. Please check password help!.
        /// </summary>
        internal static string SIGNUP_MINIMUM_PWD {
            get {
                return ResourceManager.GetString("SIGNUP_MINIMUM_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name already exists..
        /// </summary>
        internal static string SIGNUP_ORGANISATION_ALREDY_EXIST_PART_1 {
            get {
                return ResourceManager.GetString("SIGNUP_ORGANISATION_ALREDY_EXIST_PART_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try with another Organization name..
        /// </summary>
        internal static string SIGNUP_ORGANISATION_ALREDY_EXIST_PART_2 {
            get {
                return ResourceManager.GetString("SIGNUP_ORGANISATION_ALREDY_EXIST_PART_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not inserted.Please try again..
        /// </summary>
        internal static string SIGNUP_RECORD_INSERT_FAILED {
            get {
                return ResourceManager.GetString("SIGNUP_RECORD_INSERT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept Terms &amp; Conditions..
        /// </summary>
        internal static string SIGNUP_TERMS_CONDITION {
            get {
                return ResourceManager.GetString("SIGNUP_TERMS_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Id or Password.
        /// </summary>
        internal static string SITE_LOGIN_DETAIL_INVALID {
            get {
                return ResourceManager.GetString("SITE_LOGIN_DETAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin account credential required..
        /// </summary>
        internal static string SITE_LOGIN_EMAILID_AS_USER {
            get {
                return ResourceManager.GetString("SITE_LOGIN_EMAILID_AS_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email verification is pending..
        /// </summary>
        internal static string SITE_LOGIN_VERIFICATION_PENDING {
            get {
                return ResourceManager.GetString("SITE_LOGIN_VERIFICATION_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification mail sent successfully..
        /// </summary>
        internal static string SITE_LOGIN_VERIFICATION_SEND {
            get {
                return ResourceManager.GetString("SITE_LOGIN_VERIFICATION_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you have successfully verified your email id..
        /// </summary>
        internal static string SITE_LOGIN_VERIFIED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("SITE_LOGIN_VERIFIED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Subject?.
        /// </summary>
        internal static string SUBJECT_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("SUBJECT_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Submilestone?.
        /// </summary>
        internal static string SUBMILESTONE_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("SUBMILESTONE_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Submilestone already exists.
        /// </summary>
        internal static string SUBMILESTONE_DUPLICATE {
            get {
                return ResourceManager.GetString("SUBMILESTONE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        internal static string TASK_CONFIRM_DELETION {
            get {
                return ResourceManager.GetString("TASK_CONFIRM_DELETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Container Name already exists.
        /// </summary>
        internal static string TASK_CONTAINER_EXISTS {
            get {
                return ResourceManager.GetString("TASK_CONTAINER_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Task Container Name.
        /// </summary>
        internal static string TASK_CONTAINER_INVALID_NAME {
            get {
                return ResourceManager.GetString("TASK_CONTAINER_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TaskId.
        /// </summary>
        internal static string TASK_ID_INVALID {
            get {
                return ResourceManager.GetString("TASK_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Task Name.
        /// </summary>
        internal static string TASK_INVALID_NAME {
            get {
                return ResourceManager.GetString("TASK_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be earlier than finish date.
        /// </summary>
        internal static string TEMPLATE_INVALID_START_DATE {
            get {
                return ResourceManager.GetString("TEMPLATE_INVALID_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Training Title.
        /// </summary>
        internal static string TEMPLATE_INVALID_TITLE {
            get {
                return ResourceManager.GetString("TEMPLATE_INVALID_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This training name already exists, Please enter other name.
        /// </summary>
        internal static string TEMPLATE_TRAINING_NAME_EXIST {
            get {
                return ResourceManager.GetString("TEMPLATE_TRAINING_NAME_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to delete this Training?.
        /// </summary>
        internal static string TRAINING_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("TRAINING_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email for WAGmob.
        /// </summary>
        internal static string VF_SUBJECT {
            get {
                return ResourceManager.GetString("VF_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this video?.
        /// </summary>
        internal static string VIDEO_CONFIRM_DELETION {
            get {
                return ResourceManager.GetString("VIDEO_CONFIRM_DELETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some unsaved changes. Do you still want to proceed?.
        /// </summary>
        internal static string VIDEO_CONFIRM_NAV {
            get {
                return ResourceManager.GetString("VIDEO_CONFIRM_NAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields cannot be empty.
        /// </summary>
        internal static string VIDEO_FIELD_EMPTY {
            get {
                return ResourceManager.GetString("VIDEO_FIELD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video saved successfully!.
        /// </summary>
        internal static string VIDEO_SAVED {
            get {
                return ResourceManager.GetString("VIDEO_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a .mp4 file.
        /// </summary>
        internal static string VIDEO_SELECT_MP4 {
            get {
                return ResourceManager.GetString("VIDEO_SELECT_MP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video updated successfully!.
        /// </summary>
        internal static string VIDEO_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("VIDEO_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webinar added successfully!.
        /// </summary>
        internal static string WEBINAR_CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("WEBINAR_CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webinar deleted successfully!.
        /// </summary>
        internal static string WEBINAR_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("WEBINAR_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image for webinar..
        /// </summary>
        internal static string WEBINAR_IMAGE_NOT_SELECTED {
            get {
                return ResourceManager.GetString("WEBINAR_IMAGE_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size can&apos;t be more than 10 MB..
        /// </summary>
        internal static string WEBINAR_IMAGE_SIZE {
            get {
                return ResourceManager.GetString("WEBINAR_IMAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the timing of webinar..
        /// </summary>
        internal static string WEBINAR_INVALID_TIME {
            get {
                return ResourceManager.GetString("WEBINAR_INVALID_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide at least one language detail for webinar!.
        /// </summary>
        internal static string WEBINAR_LANGUAGE_DATA {
            get {
                return ResourceManager.GetString("WEBINAR_LANGUAGE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving language detail..
        /// </summary>
        internal static string WEBINAR_LANG_ERROR {
            get {
                return ResourceManager.GetString("WEBINAR_LANG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webinar updated successfully!.
        /// </summary>
        internal static string WEBINAR_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("WEBINAR_UPDATE_SUCCESS", resourceCulture);
            }
        }
    }
}
