//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserManager", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong. Please try again after some time..
        /// </summary>
        internal static string GENERAL_ERROR {
            get {
                return ResourceManager.GetString("GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added as a manager..
        /// </summary>
        internal static string MGR_ADDED {
            get {
                return ResourceManager.GetString("MGR_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some error in fetching the Manager list. Please try again!.
        /// </summary>
        internal static string MGR_EXCEPTION {
            get {
                return ResourceManager.GetString("MGR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occurred. Please try again!.
        /// </summary>
        internal static string MGR_EXPORT_ERROR {
            get {
                return ResourceManager.GetString("MGR_EXPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager has been deleted successfully!.
        /// </summary>
        internal static string MGR_MANAGER_DELETED_SUCCESS {
            get {
                return ResourceManager.GetString("MGR_MANAGER_DELETED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a manager from drop down list..
        /// </summary>
        internal static string MGR_MANAGER_NOT_SELECTED {
            get {
                return ResourceManager.GetString("MGR_MANAGER_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No manager found!.
        /// </summary>
        internal static string MGR_NO_MANAGERS_FOUND {
            get {
                return ResourceManager.GetString("MGR_NO_MANAGERS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user from the drop down list..
        /// </summary>
        internal static string MGR_NO_USER_SELECTED {
            get {
                return ResourceManager.GetString("MGR_NO_USER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred. Please try again!.
        /// </summary>
        internal static string MGR_USER_ASSIGNED_FAILED {
            get {
                return ResourceManager.GetString("MGR_USER_ASSIGNED_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users assigned successfully to Manager!.
        /// </summary>
        internal static string MGR_USER_ASSIGNED_SUCCESS {
            get {
                return ResourceManager.GetString("MGR_USER_ASSIGNED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select users to assign Manager!.
        /// </summary>
        internal static string MGR_USER_COUNT_ZERO {
            get {
                return ResourceManager.GetString("MGR_USER_COUNT_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user from the drop down list..
        /// </summary>
        internal static string MGR_USER_NOT_SELECTED {
            get {
                return ResourceManager.GetString("MGR_USER_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been removed successfully!.
        /// </summary>
        internal static string MGR_USER_REMOVED_SUCCESS {
            get {
                return ResourceManager.GetString("MGR_USER_REMOVED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor assigned successfully!.
        /// </summary>
        internal static string MM_ASSIGNED_SUCCESS {
            get {
                return ResourceManager.GetString("MM_ASSIGNED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string MM_CONFIRM_DELETION {
            get {
                return ResourceManager.GetString("MM_CONFIRM_DELETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor/Mentee deleted successfully!.
        /// </summary>
        internal static string MM_DELETED {
            get {
                return ResourceManager.GetString("MM_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again!.
        /// </summary>
        internal static string MM_ERROR {
            get {
                return ResourceManager.GetString("MM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a mentee to assign!.
        /// </summary>
        internal static string MM_NO_MENTEE_SELECTED {
            get {
                return ResourceManager.GetString("MM_NO_MENTEE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mentor found!.
        /// </summary>
        internal static string MM_NO_MENTOR {
            get {
                return ResourceManager.GetString("MM_NO_MENTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor &amp; Mentee id\&apos;s should be different..
        /// </summary>
        internal static string MM_SAME_ID {
            get {
                return ResourceManager.GetString("MM_SAME_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available for the given search..
        /// </summary>
        internal static string MM_SEARCH_NULL {
            get {
                return ResourceManager.GetString("MM_SEARCH_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the combination of mentor-mentee and then click on the Assign!.
        /// </summary>
        internal static string MM_SELECT_MENTOR_MENTEE {
            get {
                return ResourceManager.GetString("MM_SELECT_MENTOR_MENTEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the subject first!.
        /// </summary>
        internal static string MM_SUBJECT_NOT_SELECTED {
            get {
                return ResourceManager.GetString("MM_SUBJECT_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor/Mentee updated successfully!.
        /// </summary>
        internal static string MM_UPDATED {
            get {
                return ResourceManager.GetString("MM_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email Id..
        /// </summary>
        internal static string PD_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("PD_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second date should be greater than first date!.
        /// </summary>
        internal static string PD_SECOND_DATE_SMALL {
            get {
                return ResourceManager.GetString("PD_SECOND_DATE_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on edit button to update user assignment.
        /// </summary>
        internal static string SA_CLICK_EDIT {
            get {
                return ResourceManager.GetString("SA_CLICK_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one day for training.
        /// </summary>
        internal static string SA_DAY_NOT_SELECTED {
            get {
                return ResourceManager.GetString("SA_DAY_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should be greater than start date!.
        /// </summary>
        internal static string SA_END_DATE_INVALID {
            get {
                return ResourceManager.GetString("SA_END_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select end date.
        /// </summary>
        internal static string SA_END_DATE_NOT_SELECTED {
            get {
                return ResourceManager.GetString("SA_END_DATE_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group from drop down.
        /// </summary>
        internal static string SA_GROUP_SELECTED_DEFAULT {
            get {
                return ResourceManager.GetString("SA_GROUP_SELECTED_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should be greater than start date..
        /// </summary>
        internal static string SA_INVALID_END_GRID {
            get {
                return ResourceManager.GetString("SA_INVALID_END_GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time.It should be in HH:MM:SS format..
        /// </summary>
        internal static string SA_INVALID_TIME {
            get {
                return ResourceManager.GetString("SA_INVALID_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numeric value greater than zero.
        /// </summary>
        internal static string SA_LIMIT_INVALID {
            get {
                return ResourceManager.GetString("SA_LIMIT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group found!.
        /// </summary>
        internal static string SA_NO_GROUP {
            get {
                return ResourceManager.GetString("SA_NO_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one user..
        /// </summary>
        internal static string SA_NO_USER_SELECTED {
            get {
                return ResourceManager.GetString("SA_NO_USER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a schedule for training.
        /// </summary>
        internal static string SA_SCHEDULE_NULL {
            get {
                return ResourceManager.GetString("SA_SCHEDULE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose user to assign selected subject.
        /// </summary>
        internal static string SA_SELECT_USER {
            get {
                return ResourceManager.GetString("SA_SELECT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date should be equal or greater than today&apos;s date!.
        /// </summary>
        internal static string SA_START_DATE_INVALID {
            get {
                return ResourceManager.GetString("SA_START_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject assigned successfully.
        /// </summary>
        internal static string SA_SUBJECT_ASSIGNED_SUCCESS {
            get {
                return ResourceManager.GetString("SA_SUBJECT_ASSIGNED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the subject from dropdown.
        /// </summary>
        internal static string SA_SUBJECT_NOT_SELECTED {
            get {
                return ResourceManager.GetString("SA_SUBJECT_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Training found!.
        /// </summary>
        internal static string SA_TRAINING_EMPTY {
            get {
                return ResourceManager.GetString("SA_TRAINING_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter training limit.
        /// </summary>
        internal static string SA_TRAINING_LIMIT_NULL {
            get {
                return ResourceManager.GetString("SA_TRAINING_LIMIT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed for subject/subjects :.
        /// </summary>
        internal static string SA_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("SA_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved successfully!.
        /// </summary>
        internal static string SA_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("SA_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size can&apos;t be greater than 1MB.
        /// </summary>
        internal static string SETTING_IMG_SIZE_ERROR {
            get {
                return ResourceManager.GetString("SETTING_IMG_SIZE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload image to server.Please try again!.
        /// </summary>
        internal static string SETTING_IMG_UPLOAD_FAIL {
            get {
                return ResourceManager.GetString("SETTING_IMG_UPLOAD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password can&apos;t be used as new Password!.
        /// </summary>
        internal static string SETTING_OLD_NEW_PWD_SAME {
            get {
                return ResourceManager.GetString("SETTING_OLD_NEW_PWD_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user details.
        /// </summary>
        internal static string SETTING_PROFILE_INVALID_DETAIL {
            get {
                return ResourceManager.GetString("SETTING_PROFILE_INVALID_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated successfully!.
        /// </summary>
        internal static string SETTING_PROFILE_UPDATED_SUCCESS {
            get {
                return ResourceManager.GetString("SETTING_PROFILE_UPDATED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on edit button to update user assignment.
        /// </summary>
        internal static string SMA_ACTION_ASSIGN {
            get {
                return ResourceManager.GetString("SMA_ACTION_ASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose user to assign selected submilestone.
        /// </summary>
        internal static string SMA_ACTION_UNASSIGN {
            get {
                return ResourceManager.GetString("SMA_ACTION_UNASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submilestone assigned successfully!.
        /// </summary>
        internal static string SMA_ASSIGNMENT_SUCCESS {
            get {
                return ResourceManager.GetString("SMA_ASSIGNMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment updated successfully!.
        /// </summary>
        internal static string SMA_ASSIGNMENT_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("SMA_ASSIGNMENT_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a milestone from dropdown..
        /// </summary>
        internal static string SMA_INVALID_MILESTONE {
            get {
                return ResourceManager.GetString("SMA_INVALID_MILESTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No milestone found!.
        /// </summary>
        internal static string SMA_NO_MILESTONE {
            get {
                return ResourceManager.GetString("SMA_NO_MILESTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No submilestone found!.
        /// </summary>
        internal static string SMA_NO_SUBMILESTONE {
            get {
                return ResourceManager.GetString("SMA_NO_SUBMILESTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unassign selected user?.
        /// </summary>
        internal static string SMA_UNASSIGN_USER {
            get {
                return ResourceManager.GetString("SMA_UNASSIGN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subject found..
        /// </summary>
        internal static string SUBJECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SUBJECT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU deleted successfully!.
        /// </summary>
        internal static string SUBSCRIPTION_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered invalid Price!.
        /// </summary>
        internal static string SUBSCRIPTION_INVALID_AMOUNT_VAL {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_INVALID_AMOUNT_VAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity should be between 1 to 365 days!.
        /// </summary>
        internal static string SUBSCRIPTION_INVALID_VALIDITY {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_INVALID_VALIDITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SKU created successfully!.
        /// </summary>
        internal static string SUBSCRIPTION_NEW_SUCCESS {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_NEW_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU updated successfully!.
        /// </summary>
        internal static string SUBSCRIPTION_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users added successfully to this group!.
        /// </summary>
        internal static string UMC_ADD_MEMBER_SUCCESS {
            get {
                return ResourceManager.GetString("UMC_ADD_MEMBER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle name already exist. Please enter new name!.
        /// </summary>
        internal static string UMC_CIRCLE_EXIST {
            get {
                return ResourceManager.GetString("UMC_CIRCLE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle name updated successfully!.
        /// </summary>
        internal static string UMC_CIRCLE_NAME_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UMC_CIRCLE_NAME_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this circle?.
        /// </summary>
        internal static string UMC_CONFIRM_CIRCLE_DELETION {
            get {
                return ResourceManager.GetString("UMC_CONFIRM_CIRCLE_DELETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Selected Recipients?.
        /// </summary>
        internal static string UMC_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("UMC_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Recipients to Delete!.
        /// </summary>
        internal static string UMC_EMPTY_RECIPIENTS {
            get {
                return ResourceManager.GetString("UMC_EMPTY_RECIPIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somthing went wrong try again later!.
        /// </summary>
        internal static string UMC_ERROR {
            get {
                return ResourceManager.GetString("UMC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle created successfully!.
        /// </summary>
        internal static string UMC_GRP_CREATED {
            get {
                return ResourceManager.GetString("UMC_GRP_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle creation failed!.
        /// </summary>
        internal static string UMC_GRP_CREATION_FAILED {
            get {
                return ResourceManager.GetString("UMC_GRP_CREATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle deleted successfully!.
        /// </summary>
        internal static string UMC_GRP_DELETED {
            get {
                return ResourceManager.GetString("UMC_GRP_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name already exist. Please select another name!.
        /// </summary>
        internal static string UMC_GRP_EXIST {
            get {
                return ResourceManager.GetString("UMC_GRP_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle name updated!.
        /// </summary>
        internal static string UMC_GRP_UPDATED {
            get {
                return ResourceManager.GetString("UMC_GRP_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the user you want to assign in this circle.
        /// </summary>
        internal static string UMC_GRP_USER_ASSIGNMENT {
            get {
                return ResourceManager.GetString("UMC_GRP_USER_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid circle name.
        /// </summary>
        internal static string UMC_INVALID_GROUP {
            get {
                return ResourceManager.GetString("UMC_INVALID_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been removed successfully from this Circle!.
        /// </summary>
        internal static string UMC_MEMBER_REMOVED_SUCCESS {
            get {
                return ResourceManager.GetString("UMC_MEMBER_REMOVED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No circle available.
        /// </summary>
        internal static string UMC_NO_CIRCLE {
            get {
                return ResourceManager.GetString("UMC_NO_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a circle member!.
        /// </summary>
        internal static string UMC_SELECT_CRL_MEMBER {
            get {
                return ResourceManager.GetString("UMC_SELECT_CRL_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipients selected. Please select recipient!.
        /// </summary>
        internal static string UMC_SELECT_RECIPIENT {
            get {
                return ResourceManager.GetString("UMC_SELECT_RECIPIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only .xls &amp; .xlsx files can be uploaded.
        /// </summary>
        internal static string UMI_BULK_USER_FILE_TYPE_ERROR {
            get {
                return ResourceManager.GetString("UMI_BULK_USER_FILE_TYPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inserted successfully!.
        /// </summary>
        internal static string UMI_DATA_INSERTED {
            get {
                return ResourceManager.GetString("UMI_DATA_INSERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region deleted successfully!.
        /// </summary>
        internal static string UMI_DELETE_REGION_SUCCESS {
            get {
                return ResourceManager.GetString("UMI_DELETE_REGION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please drop a single file..
        /// </summary>
        internal static string UMI_DROP_MULTIPLE {
            get {
                return ResourceManager.GetString("UMI_DROP_MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:-Duplicate Email Id..
        /// </summary>
        internal static string UMI_DUPLICATE_EMAIL {
            get {
                return ResourceManager.GetString("UMI_DUPLICATE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailId already exist!.
        /// </summary>
        internal static string UMI_EMAIL_EXIST {
            get {
                return ResourceManager.GetString("UMI_EMAIL_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailId already exist..
        /// </summary>
        internal static string UMI_EMAIL_EXIST_ORG_DIFF {
            get {
                return ResourceManager.GetString("UMI_EMAIL_EXIST_ORG_DIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:-EmailId can not be more than 50 Charaters long.
        /// </summary>
        internal static string UMI_EMAIL_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("UMI_EMAIL_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailId Already Exist, Please select Another Email Id..
        /// </summary>
        internal static string UMI_EMAIL_PRESENT {
            get {
                return ResourceManager.GetString("UMI_EMAIL_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Detail.
        /// </summary>
        internal static string UMI_EXCEL_INVALID_DETAIL {
            get {
                return ResourceManager.GetString("UMI_EXCEL_INVALID_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EmailId.
        /// </summary>
        internal static string UMI_EXCEL_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("UMI_EXCEL_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide data in correct format!.
        /// </summary>
        internal static string UMI_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("UMI_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:-LastName can not be more than 30 Charaters long.
        /// </summary>
        internal static string UMI_LAST_NAME_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("UMI_LAST_NAME_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:-FistName can not be more than 30 Charaters long.
        /// </summary>
        internal static string UMI_NAME_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("UMI_NAME_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new region.
        /// </summary>
        internal static string UMI_NEW_REGION {
            get {
                return ResourceManager.GetString("UMI_NEW_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:-Organization name can not be more than 30 Charaters long.
        /// </summary>
        internal static string UMI_ORG_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("UMI_ORG_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region added successfully!.
        /// </summary>
        internal static string UMI_REGION_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("UMI_REGION_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete  SELECTED_REGION_NAME region?&lt;br&gt; If yes then all users belongs to this region will be moved to default region..
        /// </summary>
        internal static string UMI_REGION_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("UMI_REGION_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphabets are allowed!.
        /// </summary>
        internal static string UMI_REGION_NAME_INVALID {
            get {
                return ResourceManager.GetString("UMI_REGION_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region name can&apos;t be empty!.
        /// </summary>
        internal static string UMI_REGION_NAME_NULL {
            get {
                return ResourceManager.GetString("UMI_REGION_NAME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region name updated successfully!.
        /// </summary>
        internal static string UMI_REGION_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UMI_REGION_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded doesn&apos;t match the template.Please dowload template and try again!.
        /// </summary>
        internal static string UMI_TEMPLATE_INCORRECT {
            get {
                return ResourceManager.GetString("UMI_TEMPLATE_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found in uploaded file..
        /// </summary>
        internal static string UMI_TEMPLATE_NULL {
            get {
                return ResourceManager.GetString("UMI_TEMPLATE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deleted successfully!.
        /// </summary>
        internal static string UMI_USER_DELETED_SUCCESS {
            get {
                return ResourceManager.GetString("UMI_USER_DELETED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added successfully!.
        /// </summary>
        internal static string UMI_USER_INSERTED {
            get {
                return ResourceManager.GetString("UMI_USER_INSERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details updated successfully!.
        /// </summary>
        internal static string UMI_USER_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UMI_USER_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Role!.
        /// </summary>
        internal static string UMO_ALERT_SELECT_ROLE {
            get {
                return ResourceManager.GetString("UMO_ALERT_SELECT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Selected. Please select user!.
        /// </summary>
        internal static string UMO_ALERT_SELECT_USER {
            get {
                return ResourceManager.GetString("UMO_ALERT_SELECT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected user?.
        /// </summary>
        internal static string UMO_CONFIRM_USER_DELETION {
            get {
                return ResourceManager.GetString("UMO_CONFIRM_USER_DELETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string UMO_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("UMO_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data To Display!.
        /// </summary>
        internal static string UMO_NO_DATA {
            get {
                return ResourceManager.GetString("UMO_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User to Delete!.
        /// </summary>
        internal static string UMO_NO_USER_TO_DELETE {
            get {
                return ResourceManager.GetString("UMO_NO_USER_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet Only.
        /// </summary>
        internal static string UMO_VALIDATE_USER {
            get {
                return ResourceManager.GetString("UMO_VALIDATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format.
        /// </summary>
        internal static string UP_INVALID_DATE {
            get {
                return ResourceManager.GetString("UP_INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select only one user at a time.
        /// </summary>
        internal static string UP_MULTIPLE_USER_SELECTED {
            get {
                return ResourceManager.GetString("UP_MULTIPLE_USER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one item.
        /// </summary>
        internal static string UP_NO_ITEM_SELECTED {
            get {
                return ResourceManager.GetString("UP_NO_ITEM_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user..
        /// </summary>
        internal static string UP_NO_USER_SELECTED {
            get {
                return ResourceManager.GetString("UP_NO_USER_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User to Delete!.
        /// </summary>
        internal static string UP_NO_USER_TO_DELETE {
            get {
                return ResourceManager.GetString("UP_NO_USER_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Failed!.
        /// </summary>
        internal static string UP_PAYMENT_FAILED {
            get {
                return ResourceManager.GetString("UP_PAYMENT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment done successfully!.
        /// </summary>
        internal static string UP_PAYMENT_SUCCESS {
            get {
                return ResourceManager.GetString("UP_PAYMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment has been updated successfully!.
        /// </summary>
        internal static string UP_PAYMENT_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UP_PAYMENT_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select subscription to save payment.
        /// </summary>
        internal static string UP_SELECT_SUBSCRIPTION {
            get {
                return ResourceManager.GetString("UP_SELECT_SUBSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected date must be greater than today&apos;s date.
        /// </summary>
        internal static string UP_SMALLER_DATE {
            get {
                return ResourceManager.GetString("UP_SMALLER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : Please select end date as today&apos;s date to unsubscribe item for user.
        /// </summary>
        internal static string UP_UNSUBSCRIBE_NOTE {
            get {
                return ResourceManager.GetString("UP_UNSUBSCRIBE_NOTE", resourceCulture);
            }
        }
    }
}
